/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import { Image } from "@boundaryml/baml"
export interface Node {
  id: string
  type: "custom"
  position: Position
  data: NodeData
  style: Style
  
}

export interface NodeData {
  title: string
  description: string
  
}

export interface Paper {
  nodes: Node[]
  
}

export interface Position {
  x: number
  y: number
  
}

export interface Resume {
  name: string
  email: string
  experience: string[]
  skills: string[]
  
}

export interface Style {
  backgroundColor: "hsl(0, 0%, 100%)"
  color: "hsl(0, 0%, 0%)"
  borderRadius: "0.5rem"
  
}
