/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import { Image } from "@boundaryml/baml"
export interface Coordinate {
  latitude: number
  longitude: number
  
}

export interface EnvironmentalData {
  airDensity: number
  gravitationalAcceleration: number
  
}

export interface FinalResult {
  vehicles: Vehilce[]
  trafficSignals: TrafficSignal[]
  roadData: RoadData
  environmentalData: EnvironmentalData
  
}

export interface Message {
  vehicle: VehicleInfo
  message: string
  
}

export interface Resume {
  name: string
  email: string
  experience: string[]
  skills: string[]
  
}

export interface RoadData {
  speedLimit: number
  grade: number
  upstreamDistance: number
  downstreamDistance: number
  
}

export interface TrafficSignal {
  id: string
  location: Coordinate
  currentPhase: string
  timeUntilNextPhase: number
  cycleTime: number
  
}

export interface VehicleInfo {
  id: string
  role: string
  
}

export interface Vehilce {
  id: string
  type: string
  currentSpeed: number
  location: Coordinate
  mass: number
  frontalArea: number
  enginePower: number
  drivelineEfficiency: number
  role: string
  
}
