/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import { Image } from "@boundaryml/baml"
export interface Message {
  vehicle: Vehilce
  message: string
  
}

export interface Resume {
  name: string
  email: string
  experience: string[]
  skills: string[]
  
}

export interface Vehicle {
  id: string
  type: string
  currentSpeed: number
  coordinates: number[]
  mass: number
  frontalArea: number
  enginePower: number
  drivelineEfficiency: number
  currentPhase: string
  timeUntilNextPhase: number
  cycleTime: number
  speedLimit: number
  grade: number
  upstreamDistance: number
  downstreamDistance: number
  airDensity: number
  gravitationalAcceleration: number
  a0: number
  a1: number
  a2: number
  
}

export interface Vehilce {
  id: string
  role: string
  
}
